---
# tasks file for ansible/roles/docker

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
    state: present
    update_cache: true

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker's GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Set Docker repository architecture mapping
  ansible.builtin.set_fact:
    arch_mapping:
      armv6l: "armhf"
      armv7l: "armhf"
      aarch64: "arm64"
      x86_64: "amd64"
      i386: "i386"

- name: Set Docker repository architecture
  ansible.builtin.set_fact:
    docker_arch: "{{ arch_mapping[ansible_architecture] | default('amd64') }}"

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: true

- name: Install Docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is started and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
