---
# tasks file for ansible/roles/ansible

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - software-properties-common
      - ansible
    state: present
    update_cache: true
