---
# tasks file for ansible/roles/ansible

- name: Remove ansible from sudoers
  ansible.builtin.file:
    path: /etc/sudoers.d/ansible
    state: absent

- name: Remove ansible user
  ansible.builtin.user:
    name: ansible
    state: absent
    remove: true
