---
# tasks file for ansible/roles/ansible

- name: Create ansible user
  ansible.builtin.user:
    name: ansible
    state: present
    createhome: true
    shell: /bin/bash

- name: Add ansible user to sudoers
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ansible
    content: "ansible ALL=(ALL) NOPASSWD:ALL"
    mode: '0440'

- name: Create .ssh directory for ansible user
  ansible.builtin.file:
    path: /home/ansible/.ssh
    state: directory
    owner: ansible
    group: ansible
    mode: '0700'

- name: Add authorized key for ansible user
  ansible.builtin.copy:
    dest: /home/ansible/.ssh/authorized_keys
    content: "{{ lookup('file', '~/.ssh/ansible_key.pub') }}"
    owner: ansible
    group: ansible
    mode: '0600'
