---
# tasks file for ansible/roles/ansible

- name: Remove Ansible package
  ansible.builtin.apt:
    pkg:
      - ansible
      - software-properties-common
    state: absent
    purge: true

- name: Remove .ansible
  ansible.builtin.file:
    path: "~/.ansible"
    state: absent

- name: Clean up package cache
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
