---
# Setup steps for the ansible-terraform-kestra-actions control node
- name: Ansible Control Node Setup
  hosts: atlas
  become: true

  roles:
    - role: ansible
    - role: github
    - role: ubuntu

  tasks:
    - name: Ubuntu setup
      ansible.builtin.include_tasks:
        file: roles/ubuntu/tasks/ubuntu-setup.yml

    - name: Setup Github
      ansible.builtin.include_tasks:
        file: roles/github/tasks/connect-github.yml

    - name: Pull orbit repo
      ansible.builtin.git:
        repo: https://github.com/sloraris/orbit.git
        dest: /home/ansible/orbit
        key_file: /home/ansible/.ssh/ansible-github-ssh

    # TODO: install Github runner

    - name: Install Ansible
      ansible.builtin.include_tasks:
        file: roles/ansible/tasks/install-ansible.yml

    # TODO: install terraform
    # TODO: install kestra
