---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sloraris-dev
  namespace: default
spec:
  secretName: sloraris-dev-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.sloraris.dev"
  dnsNames:
  - "sloraris.dev"
  - "*.sloraris.dev"
