---
# tasks file for ansible/roles/ubuntu

- name: Update apt cache and upgrade packages
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Install packages
  ansible.builtin.apt:
    pkg:
      - git
      - openssh-server
      - openssh-client
      - curl
    update_cache: true

- name: Disable password login for root and orbit
  ansible.builtin.set_fact:
    root_password_login_disabled: true
    orbit_password_login_disabled: true

- name: Configure passwordless sudo for user
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ ansible_user }}
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: '0440'
    create: true
    validate: /usr/sbin/visudo -cf %s

- name: Install orbit ssh key
  ansible.builtin.copy:
    dest: /home/orbit/.ssh/authorized_keys
    content: "{{ lookup('file', '~/.ssh/orbit_key.pub') }}"
    owner: orbit
    group: orbit
    mode: '0600'
