---
- name: Upgrade all apt packages
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    autoremove: true
    autoclean: true

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot the system if required
  ansible.builtin.reboot:
    msg: "Rebooting due to package updates"
    reboot_timeout: 300
  when: reboot_required_file.stat.exists
